# Generated by Django 5.1.2 on 2024-10-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
